default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_api_development
  username: postgres
  password: 12358
  host: localhost


test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>