default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>]
  host: localhost
  port: 5432

development:
  <<: *default
  database: todo_api_development
  username: postgres
  password: 12358

test:
  <<: *default
  database: todo_api_test

production:
  dispatcher: true
  worker: true
  queues: "*"
  connection: 
    adapter: postgresql
    url: <%= ENV['SOLID_QUEUE_DATABASE_URL'] %>