default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>]
  host: localhost
  username: postgres
  password: 12358

development:
  <<: *default
  database: todo_api_development

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

solid_queue:
  <<: *default  # Herda a mesma conexão do ambiente atual
  migrations_paths: db/solid_queue_migrate