default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>]
  host: localhost
  port: 5432
  username: postgres
  password: 12358

development:
  <<: *default
  database: todo_api_development

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: production_bv03
  url: postgresql://production_bv03_user:qJS2rlW0yjlJeFkCFXKymOMF6Gxcb23F@dpg-cvvgibbuibrs73beiljg-a/production_bv03
  host: dpg-cvvgibbuibrs73beiljg-a
  username: production_bv03_user
  password: qJS2rlW0yjlJeFkCFXKymOMF6Gxcb23F
  port: 5432
  sslmode: require

solid_queue:
  <<: *default  # Herda a mesma conexão do ambiente atual
  migrations_paths: db/solid_queue_migrate