default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>]
  host: localhost
  port: 5432
  username: postgres
  password: 12358

development:
  <<: *default
  database: todo_api_development

test:
  <<: *default
  database: todo_api_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: <%= ENV['PGSSLMODE'] || 'require' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

solid_queue:
  <<: *default  # Herda a mesma conexão do ambiente atual
  migrations_paths: db/solid_queue_migrate